scalar DateTime

scalar JSON

type User {
  id: Int!
  email: String
  username: String
  firstName: String
  lastName: String
  createdAt: DateTime!
  updatedAt: DateTime!
  notes: [Note!]!
  goals: [Goal!]!
  relationshipsAsUser: [UserRelationship!]!
  relationshipsAsTarget: [UserRelationship!]!
  responses: [Response!]!
  questions: [Question!]!
}

type Query {
  users: usersInfoResponse
  user(id: Int, email: String, username: String): User
  notes: notesInfoResponse
  note(id: Int!): Note
  goals: GoalsInfoResponse!
  goal(id: Int!): Goal
  userRelationships(userId: Int!): UserRelationshipResponse
  questions: QuestionsInfoResponse
  question(id: Int!): Question
  responses: ResponsesInfoResponse
  response(id: Int!): Response
  canvasUserRelationships(canvasId: Int!): CanvasUserRelationshipsResponse
  canvases: CanvasesInfoResponse
  canvas(id: Int, ownerId: Int): Canvas
}

type usersInfoResponse {
  success: Boolean!
  total: Int!
  users: [User!]!
}

type Mutation {
  regUser(username: String!, email: String!, password: String!): User
  loginUser(email: String!, password: String!): User
  updateUser(id: Int!, username: String, email: String, password: String, firstName: String, lastName: String): User
  deleteUser(id: Int!): deleteResponse!
  addNote(content: String!, authorId: Int!): Note
  updateNote(id: Int!, content: String): Note
  deleteNote(id: Int!): deleteResponse!
  addGoal(content: String!, userId: Int!, dueDate: DateTime!): Goal
  updateGoal(id: Int!, content: String, dueDate: DateTime): Goal
  deleteGoal(id: Int!): deleteResponse!
  sendFriendRequest(userId: Int!, targetUserId: Int!): UserRelationship
  respondToFriendRequest(userId: Int!, targetUserId: Int!, accept: Boolean!): UserRelationship
  removeFriend(userId: Int!, targetUserId: Int!): Boolean
  blockUser(userId: Int!, targetUserId: Int!): Boolean
  addQuestion(authorId: Int!, body: String!): Question
  updateQuestion(id: Int!, body: String): Question
  deleteQuestion(id: Int!): deleteQuestion!
  addResponse(questionId: Int!, authorId: Int!, body: String!): Response
  updateResponse(id: Int!, body: String): Response
  deleteResponse(id: Int!): deleteResponse!
  addCanvasUserRelationship(canvasId: Int!, userId: Int!): CanvasUserRelationship
  deleteCanvasUserRelationship(canvasId: Int!, userId: Int!): deleteResponse!
  addCanvas(ownerId: Int!, visibility: CanvasVisibility!, drawingData: JSON): Canvas
  updateCanvas(id: Int!, visibility: CanvasVisibility, drawingData: JSON): Canvas
  deleteCanvas(id: Int!): deleteResponse!
}

type deleteResponse {
  success: Boolean!
  message: String!
  id: Int!
}

type Note {
  id: Int!
  content: String
  authorId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type notesInfoResponse {
  success: Boolean!
  total: Int!
  notes: [Note!]!
}

type Goal {
  id: Int!
  content: String
  status: GoalStatus!
  userId: Int!
  dueDate: DateTime!
  createdAt: DateTime!
  updatedAt: DateTime!
}

enum GoalStatus {
  active
  completed
  deleted
  inactive
}

type GoalsInfoResponse {
  success: Boolean!
  total: Int!
  goals: [Goal!]!
}

type UserRelationship {
  userId: Int!
  targetUserId: Int!
  status: RelationshipStatus!
  createdAt: DateTime!
}

enum RelationshipStatus {
  pending
  accepted
  rejected
  blocked
}

type UserRelationshipResponse {
  success: Boolean!
  total: Int!
  relationships: [UserRelationship!]!
}

type Question {
  id: Int!
  authorId: Int!
  body: String
  createdAt: DateTime!
  updatedAt: DateTime!
  responses: [Response!]!
}

type QuestionsInfoResponse {
  success: Boolean!
  total: Int!
  questions: [Question!]!
}

type deleteQuestion {
  success: Boolean!
  message: String!
  id: Int!
}

type Response {
  id: Int!
  questionId: Int!
  authorId: Int!
  body: String
  createdAt: DateTime!
  updatedAt: DateTime!
}

type ResponsesInfoResponse {
  success: Boolean!
  total: Int!
  responses: [Response!]!
}

type CanvasUserRelationship {
  canvasId: Int!
  userId: Int!
}

type CanvasUserRelationshipsResponse {
  success: Boolean!
  total: Int!
  canvasUserRelationships: [CanvasUserRelationship!]!
}

type Canvas {
  id: Int!
  ownerId: Int!
  visibility: CanvasVisibility!
  drawingData: JSON
  createdAt: DateTime!
  updatedAt: DateTime!
  owner: User!
  canvasUsers: [CanvasUserRelationship!]!
}

enum CanvasVisibility {
  private
  friends
  public
}

type CanvasesInfoResponse {
  success: Boolean!
  total: Int!
  canvases: [Canvas!]!
}

type Subscription {
  canvasUpdated(canvasId: Int!): Canvas
}